stages:
  - basic
  - fullinstall

# PHP 7.2 simple linting
php-7.2-linting:
  stage: basic
  image: php:7.2
  script:
    - sh -c 'if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -v "^No syntax errors detected"; then exit 1; fi'

# PHP 7.3 simple linting
php-7.3-linting:
  stage: basic
  image: php:7.3
  script:
    - sh -c 'if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -v "^No syntax errors detected"; then exit 1; fi'

# PHP 7.3 codesniffing
php-7.3-phpcs:
  stage: basic
  image: yireo/php-testbox:7.3
  script:
    - phpcs --colors --standard=PSR2 --report=full --extensions=php,phtml .
    - composer validate

# Magento MEQP2 validation
magento-eqp2-basic:
  stage: basic
  image: yireo/php-testbox:7.1
  script:
    - mkdir -p /tmp/magento-phpcs && cd /tmp/magento-phpcs && COMPOSER_MEMORY_LIMIT=-1 composer require --dev magento/magento-coding-standard
    - php /tmp/magento-phpcs/vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard/
    - php /tmp/magento-phpcs/vendor/bin/phpcs $CI_PROJECT_DIR --standard=Magento2 --severity=10 --extensions=php,phtml -s

# Magento 2.3 testing
magento-2.3-validation:
  image: yireo/magento2base:7.3
  stage: fullinstall
  script:
    - source .gitlab-ci.env && test "$RUN_MAGENTO_23" -eq "0" && exit 0
    - git clone https://gitlab.yireo.com/tools/magento2devbox.git /tmp/magento2devbox &&
      /tmp/magento2devbox/magento/scripts/install-magento.sh &&
      /tmp/magento2devbox/magento/scripts/gitlab-ci.sh
  variables:
    MAGENTO_VERSION: "2.3.5-p2"
  services:
    - name: mysql:5.7
    - name: redis

# Global variables
variables:
  # Composer handies
  COMPOSER_CACHE_DIR: "/build/cache"
  COMPOSER_ALLOW_SUPERUSER: "1"

  # Custom webfolder
  WEB_DIR: "/magento"
  DOCKER_DRIVER: overlay2

  # Magento runs
  RUN_MAGENTO_21: "1"
  RUN_MAGENTO_22: "1"
  RUN_MAGENTO_23: "1"

  # Simple flags to speed up deployment
  MAGENTO_ADD_SAMPLE_DATA: "0"
  MAGENTO_ADD_CRON: "0"
  MAGENTO_REMOVE_3PO: "0"
  DB_DUMP: "0"

  # MySQL variables, also needed by the MySQL service
  MYSQL_HOST: "mysql"
  MYSQL_USER: "magento2"
  MYSQL_PASSWORD: "magento2"
  MYSQL_DATABASE: "magento2"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "magento2"@"%";'

  # CI purpose
  RUN_PHPCS_EQP2: "1"
  RUN_PHPCS_EXTDN: "1"
  RUN_YIREO_EXTENSIONCHECKER: "1"
  RUN_PHPUNIT_UNIT_TESTS: "1"
  RUN_PHPUNIT_INTEGRATION_TESTS: "1"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - /build/cache/
    - vendor/
